version: "3"

services:
  db:
    image: mongo:4.2
    env_file: .env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports: 
      - "${DB_PORT}:27017"
    restart: always

  app:
    build: .
    command: yarn serve
    container_name: db
    depends_on: 
      - db
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/app